# Oracle DB
spring:
  datasource:
    url: jdbc:oracle:thin:@192.168.99.100:32769:xe
    username: cadmincat
    password: admincat
    driver-class: oracle.jdbc.driver.OracleDriver

# Hikari Connection Pool
    hikari:
      connection-timeout: 6000
      maximum-pool-size: 5

  jackson:
    default-property-inclusion: NON_NULL

    
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8010/eureka/